### ISSUE TITLE
`TAPPING_TERM` ignored for home-row on `bstiq` keymap

### ISSUE THREAD

**Issue by 0xcharly** [0xcharly/bastardkb-qmk#2]
cc @bstiq

**Comment by bstiq** [comment]
## Describe the Bug

Mod tap interrupts seem to be always on.



## System Information

 - Keyboard:  Charybdis 3x5 with blackill
   - Revision (if applicable):  blackpill adapter 1.1
 - Operating system: Windows 10
 - AVR GCC version:  8.4.0

 - ARM GCC version: 10.1.0


## Additional Context

- Using `charybdis-upstream-bstiq-with-vial` branch
- Enabling `IGNORE_MOD_TAP_INTERRUPT` does not seem to have any effect


Relevant `config.h` section:

```
#ifndef TAPPING_TERM
#define TAPPING_TERM 220
#endif  // TAPPING_TERM


#define TAPPING_FORCE_HOLD

//#define PERMISSIVE_HOLD
#undef PERMISSIVE_HOLD 

#define IGNORE_MOD_TAP_INTERRUPT
```

**Comment by bstiq** [comment]
Disabling vial in the config fixes this.
Leaving via enabled doesn't make a difference.
So this seems to be related to **vial** only.

Reseting the eeprom doesn't change anything.
